/**
 * ---
 * file: src/__tests__/us1-ac1.5-code-file-headers.test.ts
 * project: earthandhoney
 * purpose: Verify AC-1.5 — every new code file includes the project metadata
 *          front-matter header comment
 * created-by: dev-team
 * related-story: US-1
 * related-ac: 1.5
 * ---
 */
import fs from 'fs'
import path from 'path'

const root = process.cwd()
const CODE_EXTENSIONS = ['.ts', '.tsx', '.js', '.jsx', '.mjs']

// Mirrors eslint.config.mjs's globalIgnores: directories/files that are
// generated output or vendored template assets, not code we author.
const IGNORED_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  '.swc',
  'out',
  'build',
  'coverage',
  'logs',
  'models',
  'photobuddy',
  // Vendored PicPeak fork (US-15 AC-15.6) — upstream code held verbatim at the
  // pinned commit. It is not code we author and must never be edited, so it
  // carries upstream's headers, not ours.
  'vendor',
])
const IGNORED_FILES = new Set([
  // Auto-regenerated by Next.js on every build; carries its own
  // "This file should not be edited" notice.
  'next-env.d.ts',
  // Auto-regenerated by Payload CMS whenever admin-panel custom components
  // change (`next dev`/`next build` calls Payload's import-map generator); a
  // hand-added header would be overwritten on the next regeneration.
  'importMap.js',
])

function collectCodeFiles(dir: string, out: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (IGNORED_DIRS.has(entry.name)) continue
      collectCodeFiles(path.join(dir, entry.name), out)
    } else if (
      CODE_EXTENSIONS.includes(path.extname(entry.name)) &&
      !IGNORED_FILES.has(entry.name)
    ) {
      out.push(path.join(dir, entry.name))
    }
  }
  return out
}

const codeFiles = collectCodeFiles(root).map((f) => path.relative(root, f))

// Not anchored to the very start of the file: a file may carry another
// required docblock first (e.g. Jest's `@jest-environment` pragma), so the
// AC only requires the header to be *included* near the top, not to be the
// literal first bytes.
const HEADER_RE =
  /\/\*\*\s*\n\s*\*\s*---\s*\n\s*\*\s*file:\s*(.+?)\s*\n\s*\*\s*project:\s*(.+?)\s*\n[\s\S]*?\*\s*purpose:\s*[\s\S]*?\*\s*created-by:\s*(.+?)\s*\n[\s\S]*?\*\s*---\s*\n\s*\*\//

describe('AC-1.5: every code file includes the project metadata front-matter header', () => {
  it('finds at least one code file to check (sanity check for the walker itself)', () => {
    expect(codeFiles.length).toBeGreaterThan(0)
  })

  it.each(codeFiles)('%s includes a structured front-matter header', (rel) => {
    const src = fs.readFileSync(path.join(root, rel), 'utf8')
    const match = src.match(HEADER_RE)
    expect(match).not.toBeNull()
  })

  it.each(codeFiles)('%s header declares the correct file path and project', (rel) => {
    const src = fs.readFileSync(path.join(root, rel), 'utf8')
    const match = src.match(HEADER_RE)
    expect(match?.[1]).toBe(rel)
    expect(match?.[2]).toBe('earthandhoney')
    expect(match?.[3]?.length).toBeGreaterThan(0)
  })

  describe('previously-missing headers are now present', () => {
    const previouslyMissing = [
      'jest.config.ts',
      'jest.setup.ts',
      'eslint.config.mjs',
      'postcss.config.mjs',
    ]

    it.each(previouslyMissing)('%s is included in the scanned code files', (rel) => {
      expect(codeFiles).toContain(rel)
    })
  })

  it('does not scan vendored template, generated, or build-output files', () => {
    expect(codeFiles.some((f) => f.startsWith('public/photobuddy/'))).toBe(false)
    expect(codeFiles.some((f) => f.startsWith('coverage/'))).toBe(false)
    expect(codeFiles.some((f) => f.startsWith('vendor/'))).toBe(false)
    expect(codeFiles).not.toContain('next-env.d.ts')
  })
})
