/**
 * @jest-environment node
 */
/**
 * ---
 * file: src/__tests__/us31-ac31.6-generate-metadata.test.ts
 * project: earthandhoney
 * purpose: Verify AC-31.6's canonical-URL and Open Graph logic in the public
 *          `[slug]` route's `generateMetadata` — the pure computation half of
 *          the AC (the "generated by the system, not typed by the
 *          photographer" fallback chain), mirroring the mocked-module
 *          technique `us24-ac24.5-studio-profile-seo-output.test.tsx` used
 *          for the root layout's own `generateMetadata`: `@/lib/getPageBySlug`
 *          and `@/lib/getStudioProfile` are mocked (both import `payload`,
 *          which is ESM-only and breaks Jest's interop boundary when
 *          imported directly — see us3-ac3.5-galleries-api-read.test.ts), and
 *          `generateMetadata` is called directly against two distinct `Pages`
 *          fixtures. The real-rendered-HTML half of this AC (a live
 *          `<link rel="canonical">`/`<meta property="og:*">` tag pair and the
 *          H1/heading-level assertions) is covered separately by
 *          us31-ac31.6-live-seo-metadata.test.ts, which fetches two live
 *          pages the way us31-ac31.4-public-page-route.test.ts does — a
 *          metadata object in code is not sufficient evidence for a tag that
 *          must land in real response HTML (see US-37 AC-37.2's same rule).
 *          updated (AC-37.2): the route's description now falls back to
 *          `StudioProfile.defaultMetaDescription` instead of being left
 *          undefined — one assertion below was updated to match.
 * created-by: dev-team
 * related-story: US-31
 * related-ac: 31.6
 * updated-by: dev-team
 * related-story: US-37
 * related-ac: 37.2
 * ---
 */
import type { ResolvedPage } from '@/lib/getPageBySlug'
import type { ResolvedStudioProfile } from '@/lib/getStudioProfile'

jest.mock('@/lib/getPageBySlug', () => ({
  getPageBySlug: jest.fn(),
}))
jest.mock('@/lib/getStudioProfile', () => ({
  getStudioProfile: jest.fn(),
}))

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { getPageBySlug } = require('@/lib/getPageBySlug') as { getPageBySlug: jest.Mock }
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { getStudioProfile } = require('@/lib/getStudioProfile') as { getStudioProfile: jest.Mock }
// Imported after both mocks are declared, matching us24-ac24.5's ordering —
// generateMetadata must call the mocked readers, not the real ones.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const RouteModule = require('@/app/(frontend)/[slug]/page')
const { generateMetadata } = RouteModule as {
  generateMetadata: (props: { params: Promise<{ slug: string }> }) => Promise<import('next').Metadata>
}

function page(overrides: Partial<ResolvedPage> = {}): ResolvedPage {
  return {
    heading: 'Default Heading',
    shortIntroduction: '',
    seoTitle: '',
    metaDescription: '',
    status: 'published',
    indexing: 'index',
    galleryPlacements: [],
    socialImage: null,
    template: 'standard',
    ...overrides,
  }
}

function studioProfile(overrides: Partial<ResolvedStudioProfile> = {}): ResolvedStudioProfile {
  return {
    businessName: 'Earth & Honey Studios',
    description: '',
    defaultTitlePattern: '%s | Earth & Honey Studios',
    defaultMetaDescription: 'Studio default description.',
    publicPhone: '',
    publicEmail: '',
    address: { street: '', city: '', region: '', postalCode: '', country: '' },
    serviceAreas: [],
    socialProfiles: [],
    defaultSocialImage: null,
    homeHeroGallerySlug: null,
    homeSelectedGalleriesOrStories: [],
    ...overrides,
  }
}

async function metadataFor(slug: string): Promise<import('next').Metadata> {
  return generateMetadata({ params: Promise.resolve({ slug }) })
}

describe('US-31 AC-31.6: generateMetadata computes canonical URL and Open Graph data, not typed fields', () => {
  afterEach(() => {
    getPageBySlug.mockReset()
    getStudioProfile.mockReset()
  })

  it('the Pages collection has no canonical-URL or Open Graph input field — this data is system-generated only', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { Pages } = require('@/collections/Pages') as typeof import('@/collections/Pages')
    type NamedField = Extract<(typeof Pages.fields)[number], { name: string }>
    const fieldNames = Pages.fields
      .filter((field): field is NamedField => 'name' in field)
      .map((f) => f.name)
    expect(fieldNames).not.toContain('canonicalUrl')
    expect(fieldNames).not.toContain('openGraphTitle')
    expect(fieldNames).not.toContain('openGraphDescription')
    expect(fieldNames).not.toContain('openGraphImage')
  })

  it('derives alternates.canonical from the slug alone, differing between two pages at different slugs', async () => {
    getStudioProfile.mockResolvedValue(studioProfile())

    getPageBySlug.mockResolvedValue(page({ heading: 'Page A' }))
    const metaA = await metadataFor('page-a')

    getPageBySlug.mockResolvedValue(page({ heading: 'Page B' }))
    const metaB = await metadataFor('page-b')

    expect(metaA.alternates).toEqual({ canonical: '/page-a' })
    expect(metaB.alternates).toEqual({ canonical: '/page-b' })
    expect(metaA.alternates).not.toEqual(metaB.alternates)
  })

  it('Open Graph title/description/url mirror the page fields and the same canonical path, differing between two pages', async () => {
    getStudioProfile.mockResolvedValue(studioProfile())

    getPageBySlug.mockResolvedValue(
      page({ heading: 'Fallback Heading A', seoTitle: 'SEO Title A', metaDescription: 'Description A' }),
    )
    const metaA = await metadataFor('page-a')

    getPageBySlug.mockResolvedValue(
      page({ heading: 'Fallback Heading B', seoTitle: 'SEO Title B', metaDescription: 'Description B' }),
    )
    const metaB = await metadataFor('page-b')

    expect(metaA.openGraph).toMatchObject({ title: 'SEO Title A', description: 'Description A', url: '/page-a' })
    expect(metaB.openGraph).toMatchObject({ title: 'SEO Title B', description: 'Description B', url: '/page-b' })
    expect(metaA.openGraph).not.toEqual(metaB.openGraph)
  })

  it('falls back the Open Graph title to the heading, and the description to StudioProfile.defaultMetaDescription, when seoTitle/metaDescription are unset', async () => {
    getStudioProfile.mockResolvedValue(studioProfile({ defaultMetaDescription: 'Studio default description.' }))
    getPageBySlug.mockResolvedValue(page({ heading: 'Heading Only', seoTitle: '', metaDescription: '' }))

    const meta = await metadataFor('heading-only')

    // AC-37.2: description now falls back to StudioProfile.defaultMetaDescription
    // rather than being left undefined — see us37-ac37.2-generate-metadata-fallback-and-twitter.test.ts
    // for the full fallback-chain coverage this AC added.
    expect(meta.openGraph).toMatchObject({ title: 'Heading Only', description: 'Studio default description.' })
  })

  it("uses the page's own socialImage for the Open Graph image when set", async () => {
    getStudioProfile.mockResolvedValue(studioProfile({ defaultSocialImage: { url: '/media/studio-default-og.jpg' } }))
    getPageBySlug.mockResolvedValue(page({ socialImage: '/media/page-specific-og.jpg' }))

    const meta = await metadataFor('page-with-image')

    expect(meta.openGraph).toMatchObject({ images: [{ url: '/media/page-specific-og.jpg' }] })
  })

  it("falls back to StudioProfile.defaultSocialImage when the page defines no socialImage", async () => {
    getStudioProfile.mockResolvedValue(studioProfile({ defaultSocialImage: { url: '/media/studio-default-og.jpg' } }))
    getPageBySlug.mockResolvedValue(page({ socialImage: null }))

    const meta = await metadataFor('page-without-image')

    expect(meta.openGraph).toMatchObject({ images: [{ url: '/media/studio-default-og.jpg' }] })
  })

  it('omits Open Graph images entirely when neither the page nor StudioProfile define one', async () => {
    getStudioProfile.mockResolvedValue(studioProfile({ defaultSocialImage: null }))
    getPageBySlug.mockResolvedValue(page({ socialImage: null }))

    const meta = await metadataFor('page-without-any-image')

    expect(meta.openGraph).toMatchObject({ images: undefined })
  })

  it('returns no canonical/Open Graph data for an unpublished or missing page', async () => {
    getStudioProfile.mockResolvedValue(studioProfile())
    getPageBySlug.mockResolvedValue(page({ status: 'draft' }))

    const meta = await metadataFor('a-draft-page')

    expect(meta.alternates).toBeUndefined()
    expect(meta.openGraph).toBeUndefined()
  })
})
