/**
 * ---
 * file: src/__tests__/us8-ac8.4-metadata-and-favicon.test.tsx
 * project: earthandhoney
 * purpose: Verify AC-8.4 — the frontend `<head>`/metadata is real (earthandhoney
 *          site title, description, favicon) and no "Create Next App" /
 *          "Generated by create next app" strings remain anywhere in the
 *          frontend shell.
 * created-by: dev-team
 * related-story: US-8
 * related-ac: 8.4
 * ---
 */
import fs from 'fs'
import path from 'path'

import { metadata } from '@/app/(frontend)/layout'

const root = process.cwd()
const read = (rel: string) => fs.readFileSync(path.join(root, rel), 'utf8')

const FAVICON_PATH = 'src/app/favicon.ico'
const TEMPLATE_FAVICON_PATH = 'public/photobuddy/img/favicon.ico'

/**
 * The "frontend shell" = every source file in the public route group plus the
 * layout components it composes. Walked rather than hard-coded so a future file
 * that reintroduces a placeholder string cannot slip past this AC.
 */
const SHELL_DIRS = ['src/app/(frontend)', 'src/components/layout']

const walk = (rel: string): string[] =>
  fs.readdirSync(path.join(root, rel), { withFileTypes: true }).flatMap((entry) => {
    const child = `${rel}/${entry.name}`
    return entry.isDirectory() ? walk(child) : [child]
  })

const FRONTEND_SHELL_FILES = SHELL_DIRS.flatMap(walk)

describe('AC-8.4: the root layout exports real earthandhoney metadata', () => {
  it('sets a real site title mentioning Earth & Honey (not the create-next-app placeholder)', () => {
    const title = metadata.title as { default?: string; template?: string }

    expect(title.default).toMatch(/Earth\s*&\s*Honey/i)
    expect(title.template).toMatch(/Earth\s*&\s*Honey/i)
    expect(title.default).not.toMatch(/Create Next App/i)
  })

  it('sets a real, non-empty description (not the create-next-app placeholder)', () => {
    expect(typeof metadata.description).toBe('string')
    expect((metadata.description as string).length).toBeGreaterThan(20)
    expect(metadata.description).not.toMatch(/generated by create next app/i)
  })

  it('points the favicon icon at /favicon.ico', () => {
    const icons = metadata.icons as { icon?: string }

    expect(icons.icon).toBe('/favicon.ico')
  })
})

describe('AC-8.4: the favicon file itself is the real earthandhoney/template icon, not the create-next-app default', () => {
  it('ships a favicon at the app root so Next.js serves it at /favicon.ico', () => {
    expect(fs.existsSync(path.join(root, FAVICON_PATH))).toBe(true)
  })

  it('src/app/favicon.ico is byte-identical to the photobuddy template favicon', () => {
    const shipped = fs.readFileSync(path.join(root, FAVICON_PATH))
    const template = fs.readFileSync(path.join(root, TEMPLATE_FAVICON_PATH))

    expect(shipped.equals(template)).toBe(true)
  })
})

describe('AC-8.4: no create-next-app placeholder strings remain anywhere in the frontend shell', () => {
  it('walks a non-empty set of frontend shell files', () => {
    expect(FRONTEND_SHELL_FILES.length).toBeGreaterThan(0)
    expect(FRONTEND_SHELL_FILES).toContain('src/app/(frontend)/layout.tsx')
    expect(FRONTEND_SHELL_FILES).toContain('src/app/(frontend)/page.tsx')
    expect(FRONTEND_SHELL_FILES).toContain('src/app/(frontend)/globals.css')
  })

  it.each(FRONTEND_SHELL_FILES)('%s contains no "Create Next App" / "Generated by create next app" strings', (file) => {
    const src = read(file)

    expect(src).not.toMatch(/create next app/i)
    expect(src).not.toMatch(/create-next-app/i)
  })
})
