/**
 * ---
 * file: src/app/(frontend)/layout.tsx
 * project: earthandhoney
 * purpose: Root layout for the public-facing Next.js route group, kept separate from the (payload) admin route group
 * created-by: dev-team
 * related-story: US-1
 * related-ac: 1.1
 * updated-by: dev-team
 * related-story: US-8
 * related-ac: 8.1
 * updated-by: dev-team
 * related-story: US-8
 * related-ac: 8.2
 * ---
 */
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { PublicShell } from "@/components/layout/PublicShell";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} h-full antialiased`}>
      <body className="min-h-full">
        <PublicShell>{children}</PublicShell>
      </body>
    </html>
  );
}
