/**
 * ---
 * file: src/app/(payload)/admin/importMap.js
 * project: earthandhoney
 * purpose: Payload admin component import map — regenerated by `payload generate:importmap` as custom admin components are added
 * created-by: dev-team
 * related-story: US-1
 * related-ac: 1.1
 * ---
 */
export const importMap = {}
